x-volume-install:
  &volume-install
    type: bind
    source: /Users/robburgers/PhpstormProjects/zwaste
    target: /var/www/html

services:
  httpd:
    container_name: httpd
    build:
      context: .docker
      dockerfile: ${PHP_DOCKERFILE}
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - DOMAIN=${DOMAIN}
    image: z-waste-httpd:${PHP_VERSION}
    ports:
      - "80:80"
      - "443:443"
      - "5173:5173"
    volumes:
      - <<: *volume-install
      - ./.docker/httpd/cert/${CERT}:/etc/apache2/ssl/cert.pem
      - ./.docker/httpd/cert/${KEY}:/etc/apache2/ssl/key.pem
      #- /Users/robburgers/PhpstormProjects/zwaste-2026/zwaste-integration-layer/config/zoink:/var/www/html/vendor/opzet-bv/zoink-config
      #- /Users/robburgers/PhpstormProjects/zwaste-2026/zwaste-integration-layer/packages/zoink-integration:/var/www/html/vendor/opzet-bv/zoink-integration
    depends_on:
      - mysql
      - mailhog
    extra_hosts:
      - "svn.loki.dev:192.168.0.26"

  composer:
    container_name: composer
    image: z-waste-httpd:${PHP_VERSION}
    volumes:
      - <<: *volume-install
      #- /Users/robburgers/PhpstormProjects/zwaste-2026/zwaste-integration-layer/config/zoink:/var/www/html/vendor/opzet-bv/zoink-config
      #- /Users/robburgers/PhpstormProjects/zwaste-2026/zwaste-integration-layer/packages/zoink-integration:/var/www/html/vendor/opzet-bv/zoink-integration
      - /Users/robburgers/.subversion:/root/.subversion
      - $SSH_AUTH_SOCK:/ssh-agent
    dns:
      - 192.168.0.1
    depends_on:
      - httpd
    environment:
      - XDEBUG_MODE=off
      - SSH_AUTH_SOCK=/ssh-agent
    entrypoint: [ 'composer' ]


  artisan:
    container_name: artisan
    image: z-waste-httpd:${PHP_VERSION}
    environment:
      - PHP_IDE_CONFIG=serverName=httpd
    volumes:
      - <<: *volume-install
    tty: true
    depends_on:
      - httpd
      - mysql
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    extra_hosts:
      - "svn.loki.dev:192.168.0.26"

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-zcalendar}
      MYSQL_USER: ${DB_USERNAME:-zcalendar}
      MYSQL_PASSWORD: ${DB_PASSWORD:-zcalendar}
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: ${DB_HOST:-mysql}
    command: [ "--log_bin_trust_function_creators=1", "--local-infile=1" ]
    volumes:
      - ${HOST_DB_PATH:-/Users/robburgers/PhpstormProjects}/${CLIENT_NAME}:/var/lib/mysql

  npm:
    container_name: npm
    image: npm:latest
    build:
      context: .docker
      dockerfile: npm.dockerfile
      ssh:
        - default
      args:
        - NPM_TOKEN=${NPM_TOKEN}
        - NODE_VERSION=${NODE_VERSION}
        - NPM_VERSION=${NPM_VERSION}
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    volumes:
      - <<: *volume-install
      - type: bind
        source: /run/host-services/ssh-auth.sock
        target: /run/host-services/ssh-auth.sock
    ports:
      - "3000:3000"
      - "3001:3001"
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]

  mailhog:
    container_name: mailhog
    image: ${MAILHOG_IMAGE:-jcalonso/mailhog}:latest
    ports:
      - "1025:1025"
      - "8025:8025"
